# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: FingLtd.Fing
PackageVersion: 3.7.2.634
PackageLocale: en-US
Publisher: Fing Ltd
PublisherUrl: https://www.fing.com/
PublisherSupportUrl: https://help.fing.com/hc/en-us
PrivacyUrl: https://www.fing.com/fing-privacy-policy/
Author: Fing Ltd
PackageName: Fing
PackageUrl: https://www.fing.com/desktop/
License: Proprietary
LicenseUrl: https://www.fing.com/fing-terms-of-service/
Copyright: Copyright © 2021 Fing Ltd
ShortDescription: Fing Desktop App
Description: Fing is a network scanning tool that helps you discover and troubleshoot devices on your network. With Fing Desktop, you can quickly see all devices connected to your Wi-Fi or Ethernet network, gain insights into their details, and analyze your network's performance. It provides real-time alerts, advanced device identification, and easy-to-use tools for managing your network. Fing is a must-have tool for network administrators and home users alike.
Moniker: fing
Tags:
- network
- network-scanner
- wifi
- network-management
- device-discovery
- troubleshooting
- it
- security
- monitoring
ReleaseNotesUrl: https://help.fing.com/hc/en-us/articles/4418318615442-Fing-Desktop-Release-Notes
PurchaseUrl: https://www.fing.com/products/
ManifestType: defaultLocale
ManifestVersion: 1.6.0
