# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: FingLtd.Fing
PackageVersion: 3.7.2.634
InstallerType: exe
Installers:
- Architecture: x86
  InstallerUrl: https://get.fing.com/fing-desktop-releases/win/Fing.exe
  InstallerSha256: 8D7D646325319CCC3E5C81D96F1DB3ED39CBBDCD6A3816702222FA7CD6678478
ManifestType: installer
ManifestVersion: 1.6.0
